# Generated by Django 6.0.3 on 2026-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
