# Generated by Django 6.0.3 on 2026-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctorprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
    ]
