# Generated by Django 6.0.3 on 2026-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='exp',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='qualifn',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
