# Generated by Django 6.0.3 on 2026-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_exp_doctorprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
