# Generated by Django 6.0.3 on 2026-04-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_doctorprofile_name_patientprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients'),
        ),
    ]
