# Generated by Django 6.0.3 on 2026-04-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_appointment_description_appointment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(blank=True, max_length=100, null=True)),
                ('reportfile', models.FileField(upload_to='labreports')),
                ('uploadedby', models.CharField(choices=[('patient', 'Patient'), ('lab', 'Lab')], max_length=20)),
                ('uploadedat', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientprofile')),
            ],
        ),
    ]
