# Generated by Django 6.0.3 on 2026-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='uploadedby',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Lab', 'Lab')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
