# Generated by Django 6.0.3 on 2026-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_appointment_phone_alter_labreport_uploadedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_to',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualfctn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
